# Generated by Django 3.1.6 on 2021-07-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glavbudgetclass',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания действия записи'),
        ),
    ]
