# Generated by Django 3.1.6 on 2021-07-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0002_auto_20210730_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Код'),
        ),
    ]
